
  - name: install MySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: install botocore and boto3 
    ansible.builtin.pip:
       name: 
         - botocore
         - boto3
       executable: pip3.9
       

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: yes

  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1